<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Adición A4 — Listas de precios (§24.5).
 * Crea price_lists y price_list_items, y asigna una lista opcional al cliente.
 */
final class Version20260712150000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Crea price_lists, price_list_items y customers.price_list_id (Adición A4)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE price_lists (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(30) NOT NULL, name VARCHAR(100) NOT NULL, is_default BOOLEAN DEFAULT false NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uq_price_list_code ON price_lists (code) WHERE (deleted_at IS NULL)');

        $this->addSql('CREATE TABLE price_list_items (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, price_list_id INT NOT NULL, subject_type VARCHAR(40) NOT NULL, subject_id INT NOT NULL, subject_label VARCHAR(200) NOT NULL, price NUMERIC(12, 2) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_price_list_item_subject ON price_list_items (subject_type, subject_id)');
        $this->addSql('CREATE UNIQUE INDEX uq_price_list_item ON price_list_items (price_list_id, subject_type, subject_id)');
        $this->addSql('CREATE INDEX IDX_price_list_items_list ON price_list_items (price_list_id)');
        $this->addSql('ALTER TABLE price_list_items ADD CONSTRAINT fk_price_list_items_list FOREIGN KEY (price_list_id) REFERENCES price_lists (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('ALTER TABLE customers ADD price_list_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE customers ADD CONSTRAINT fk_customers_price_list FOREIGN KEY (price_list_id) REFERENCES price_lists (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_customers_price_list ON customers (price_list_id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE customers DROP CONSTRAINT fk_customers_price_list');
        $this->addSql('DROP INDEX IDX_customers_price_list');
        $this->addSql('ALTER TABLE customers DROP price_list_id');
        $this->addSql('ALTER TABLE price_list_items DROP CONSTRAINT fk_price_list_items_list');
        $this->addSql('DROP TABLE price_list_items');
        $this->addSql('DROP TABLE price_lists');
    }
}
