<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260711141156 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE kardex_movements (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, movement_type VARCHAR(20) NOT NULL, quantity INT NOT NULL, unit_cost NUMERIC(12, 2) DEFAULT NULL, balance_after INT NOT NULL, reference VARCHAR(100) DEFAULT NULL, notes VARCHAR(200) DEFAULT NULL, username VARCHAR(100) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, spare_part_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D38AA0A049B7A72 ON kardex_movements (spare_part_id)');
        $this->addSql('CREATE INDEX idx_kardex_part_date ON kardex_movements (spare_part_id, created_at)');
        $this->addSql('CREATE INDEX idx_kardex_type ON kardex_movements (movement_type)');
        $this->addSql('CREATE TABLE spare_parts (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, internal_code VARCHAR(20) NOT NULL, part_code VARCHAR(40) NOT NULL, barcode VARCHAR(50) DEFAULT NULL, description VARCHAR(200) NOT NULL, unit_of_measure VARCHAR(20) DEFAULT \'UNIDAD\' NOT NULL, stock INT DEFAULT 0 NOT NULL, min_stock INT DEFAULT 0 NOT NULL, max_stock INT DEFAULT NULL, purchase_price NUMERIC(12, 2) DEFAULT NULL, sale_price NUMERIC(12, 2) DEFAULT NULL, location VARCHAR(100) DEFAULT NULL, last_purchase_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, brand_id INT DEFAULT NULL, category_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D4578A0F44F5D008 ON spare_parts (brand_id)');
        $this->addSql('CREATE INDEX IDX_D4578A0F12469DE2 ON spare_parts (category_id)');
        $this->addSql('CREATE INDEX idx_part_barcode ON spare_parts (barcode)');
        $this->addSql('CREATE INDEX idx_part_description ON spare_parts (description)');
        $this->addSql('CREATE UNIQUE INDEX uq_part_internal_code ON spare_parts (internal_code) WHERE (deleted_at IS NULL)');
        $this->addSql('CREATE UNIQUE INDEX uq_part_code ON spare_parts (part_code) WHERE (deleted_at IS NULL)');
        $this->addSql('CREATE TABLE spare_part_compatibility (spare_part_id INT NOT NULL, motorcycle_model_id INT NOT NULL, PRIMARY KEY (spare_part_id, motorcycle_model_id))');
        $this->addSql('CREATE INDEX IDX_3EA274B149B7A72 ON spare_part_compatibility (spare_part_id)');
        $this->addSql('CREATE INDEX IDX_3EA274B1D77B88EC ON spare_part_compatibility (motorcycle_model_id)');
        $this->addSql('ALTER TABLE kardex_movements ADD CONSTRAINT FK_D38AA0A049B7A72 FOREIGN KEY (spare_part_id) REFERENCES spare_parts (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE spare_parts ADD CONSTRAINT FK_D4578A0F44F5D008 FOREIGN KEY (brand_id) REFERENCES catalog_items (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE spare_parts ADD CONSTRAINT FK_D4578A0F12469DE2 FOREIGN KEY (category_id) REFERENCES catalog_items (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE spare_part_compatibility ADD CONSTRAINT FK_3EA274B149B7A72 FOREIGN KEY (spare_part_id) REFERENCES spare_parts (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE spare_part_compatibility ADD CONSTRAINT FK_3EA274B1D77B88EC FOREIGN KEY (motorcycle_model_id) REFERENCES motorcycle_models (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE kardex_movements DROP CONSTRAINT FK_D38AA0A049B7A72');
        $this->addSql('ALTER TABLE spare_parts DROP CONSTRAINT FK_D4578A0F44F5D008');
        $this->addSql('ALTER TABLE spare_parts DROP CONSTRAINT FK_D4578A0F12469DE2');
        $this->addSql('ALTER TABLE spare_part_compatibility DROP CONSTRAINT FK_3EA274B149B7A72');
        $this->addSql('ALTER TABLE spare_part_compatibility DROP CONSTRAINT FK_3EA274B1D77B88EC');
        $this->addSql('DROP TABLE kardex_movements');
        $this->addSql('DROP TABLE spare_parts');
        $this->addSql('DROP TABLE spare_part_compatibility');
    }
}
