<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260711145815 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE sale_items (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, item_type VARCHAR(20) NOT NULL, description VARCHAR(250) NOT NULL, quantity INT NOT NULL, unit_price NUMERIC(12, 2) NOT NULL, discount NUMERIC(12, 2) NOT NULL, line_total NUMERIC(12, 2) NOT NULL, sale_id INT NOT NULL, spare_part_id INT DEFAULT NULL, motorcycle_unit_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_31C2B1CE4A7E4868 ON sale_items (sale_id)');
        $this->addSql('CREATE INDEX IDX_31C2B1CE49B7A72 ON sale_items (spare_part_id)');
        $this->addSql('CREATE INDEX IDX_31C2B1CE27E831E5 ON sale_items (motorcycle_unit_id)');
        $this->addSql('CREATE TABLE sale_payments (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, amount NUMERIC(12, 2) NOT NULL, reference VARCHAR(100) DEFAULT NULL, username VARCHAR(100) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, sale_id INT NOT NULL, payment_method_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7BA677985AA1164F ON sale_payments (payment_method_id)');
        $this->addSql('CREATE INDEX idx_sale_payment_sale ON sale_payments (sale_id)');
        $this->addSql('CREATE TABLE sales (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, sale_number VARCHAR(20) NOT NULL, sale_date DATE NOT NULL, seller VARCHAR(100) NOT NULL, status VARCHAR(15) DEFAULT \'COTIZACION\' NOT NULL, subtotal NUMERIC(12, 2) NOT NULL, igv NUMERIC(12, 2) NOT NULL, total NUMERIC(12, 2) NOT NULL, paid_amount NUMERIC(12, 2) NOT NULL, payment_status VARCHAR(10) DEFAULT \'PENDIENTE\' NOT NULL, reservation_expires_at DATE DEFAULT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, notes TEXT DEFAULT NULL, customer_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6B8170449395C3F3 ON sales (customer_id)');
        $this->addSql('CREATE INDEX idx_sale_status ON sales (status)');
        $this->addSql('CREATE INDEX idx_sale_date ON sales (sale_date)');
        $this->addSql('CREATE UNIQUE INDEX uq_sale_number ON sales (sale_number)');
        $this->addSql('ALTER TABLE sale_items ADD CONSTRAINT FK_31C2B1CE4A7E4868 FOREIGN KEY (sale_id) REFERENCES sales (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sale_items ADD CONSTRAINT FK_31C2B1CE49B7A72 FOREIGN KEY (spare_part_id) REFERENCES spare_parts (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sale_items ADD CONSTRAINT FK_31C2B1CE27E831E5 FOREIGN KEY (motorcycle_unit_id) REFERENCES motorcycle_units (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sale_payments ADD CONSTRAINT FK_7BA677984A7E4868 FOREIGN KEY (sale_id) REFERENCES sales (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sale_payments ADD CONSTRAINT FK_7BA677985AA1164F FOREIGN KEY (payment_method_id) REFERENCES catalog_items (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sales ADD CONSTRAINT FK_6B8170449395C3F3 FOREIGN KEY (customer_id) REFERENCES customers (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE sale_items DROP CONSTRAINT FK_31C2B1CE4A7E4868');
        $this->addSql('ALTER TABLE sale_items DROP CONSTRAINT FK_31C2B1CE49B7A72');
        $this->addSql('ALTER TABLE sale_items DROP CONSTRAINT FK_31C2B1CE27E831E5');
        $this->addSql('ALTER TABLE sale_payments DROP CONSTRAINT FK_7BA677984A7E4868');
        $this->addSql('ALTER TABLE sale_payments DROP CONSTRAINT FK_7BA677985AA1164F');
        $this->addSql('ALTER TABLE sales DROP CONSTRAINT FK_6B8170449395C3F3');
        $this->addSql('DROP TABLE sale_items');
        $this->addSql('DROP TABLE sale_payments');
        $this->addSql('DROP TABLE sales');
    }
}
