<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260711144558 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE cash_movements (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, movement_type VARCHAR(10) NOT NULL, amount NUMERIC(12, 2) NOT NULL, concept VARCHAR(200) NOT NULL, reference VARCHAR(100) DEFAULT NULL, username VARCHAR(100) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, session_id INT NOT NULL, payment_method_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_DD9448DD613FECDF ON cash_movements (session_id)');
        $this->addSql('CREATE INDEX IDX_DD9448DD5AA1164F ON cash_movements (payment_method_id)');
        $this->addSql('CREATE INDEX idx_cash_mov_session ON cash_movements (session_id, created_at)');
        $this->addSql('CREATE TABLE cash_sessions (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, session_number VARCHAR(20) NOT NULL, opened_by VARCHAR(100) NOT NULL, opened_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, opening_amount NUMERIC(12, 2) NOT NULL, closed_by VARCHAR(100) DEFAULT NULL, closed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, counted_amount NUMERIC(12, 2) DEFAULT NULL, expected_amount NUMERIC(12, 2) DEFAULT NULL, difference NUMERIC(12, 2) DEFAULT NULL, status VARCHAR(10) DEFAULT \'ABIERTA\' NOT NULL, notes TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_cash_session_status ON cash_sessions (status)');
        $this->addSql('CREATE UNIQUE INDEX uq_cash_session_number ON cash_sessions (session_number)');
        $this->addSql('ALTER TABLE cash_movements ADD CONSTRAINT FK_DD9448DD613FECDF FOREIGN KEY (session_id) REFERENCES cash_sessions (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cash_movements ADD CONSTRAINT FK_DD9448DD5AA1164F FOREIGN KEY (payment_method_id) REFERENCES catalog_items (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE cash_movements DROP CONSTRAINT FK_DD9448DD613FECDF');
        $this->addSql('ALTER TABLE cash_movements DROP CONSTRAINT FK_DD9448DD5AA1164F');
        $this->addSql('DROP TABLE cash_movements');
        $this->addSql('DROP TABLE cash_sessions');
    }
}
