<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Adición A3 — Historial de precios (§24.4).
 * Tabla transversal append-only de cambios de precio, con motivo y usuario.
 */
final class Version20260712120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Crea la tabla price_history (Adición A3 · historial de precios)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE price_history (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, subject_type VARCHAR(40) NOT NULL, subject_id INT NOT NULL, subject_label VARCHAR(200) NOT NULL, old_price NUMERIC(12, 2) DEFAULT NULL, new_price NUMERIC(12, 2) DEFAULT NULL, reason VARCHAR(255) DEFAULT NULL, username VARCHAR(100) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_price_history_subject ON price_history (subject_type, subject_id)');
        $this->addSql('CREATE INDEX idx_price_history_created_at ON price_history (created_at)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE price_history');
    }
}
