<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260711150421 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE document_series (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, doc_type VARCHAR(2) NOT NULL, series VARCHAR(4) NOT NULL, last_correlative INT DEFAULT 0 NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uq_series ON document_series (doc_type, series)');
        $this->addSql('CREATE TABLE electronic_documents (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, doc_type VARCHAR(2) NOT NULL, series VARCHAR(4) NOT NULL, correlative INT NOT NULL, issue_date DATE NOT NULL, customer_name VARCHAR(200) NOT NULL, customer_doc_type VARCHAR(15) NOT NULL, customer_doc_number VARCHAR(20) NOT NULL, customer_address VARCHAR(200) DEFAULT NULL, subtotal NUMERIC(12, 2) NOT NULL, igv NUMERIC(12, 2) NOT NULL, total NUMERIC(12, 2) NOT NULL, status VARCHAR(10) DEFAULT \'PENDIENTE\' NOT NULL, hash VARCHAR(40) DEFAULT NULL, qr_data TEXT DEFAULT NULL, xml TEXT DEFAULT NULL, cdr TEXT DEFAULT NULL, error_message TEXT DEFAULT NULL, provider_response JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, sale_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_58EAF0384A7E4868 ON electronic_documents (sale_id)');
        $this->addSql('CREATE INDEX idx_document_status ON electronic_documents (status)');
        $this->addSql('CREATE INDEX idx_document_issue_date ON electronic_documents (issue_date)');
        $this->addSql('CREATE UNIQUE INDEX uq_document_number ON electronic_documents (doc_type, series, correlative)');
        $this->addSql('ALTER TABLE electronic_documents ADD CONSTRAINT FK_58EAF0384A7E4868 FOREIGN KEY (sale_id) REFERENCES sales (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE electronic_documents DROP CONSTRAINT FK_58EAF0384A7E4868');
        $this->addSql('DROP TABLE document_series');
        $this->addSql('DROP TABLE electronic_documents');
    }
}
