<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Guías de Remisión Electrónica (GRE Remitente). Módulo independiente.
 */
final class Version20260814150000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Crea la tabla dispatch_guides (guías de remisión)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE IF NOT EXISTS dispatch_guides (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                series VARCHAR(4) NOT NULL,
                correlative INT NOT NULL,
                issue_date DATE NOT NULL,
                transfer_date DATE NOT NULL,
                motive VARCHAR(2) NOT NULL,
                recipient_doc_type VARCHAR(15) NOT NULL,
                recipient_doc_number VARCHAR(20) NOT NULL,
                recipient_name VARCHAR(200) NOT NULL,
                origin_address VARCHAR(200) NOT NULL,
                origin_ubigeo VARCHAR(6) DEFAULT NULL,
                destination_address VARCHAR(200) NOT NULL,
                destination_ubigeo VARCHAR(6) DEFAULT NULL,
                transport_mode VARCHAR(2) NOT NULL,
                carrier_ruc VARCHAR(11) DEFAULT NULL,
                carrier_name VARCHAR(200) DEFAULT NULL,
                vehicle_plate VARCHAR(20) DEFAULT NULL,
                driver_license VARCHAR(20) DEFAULT NULL,
                driver_name VARCHAR(200) DEFAULT NULL,
                total_weight NUMERIC(10, 3) NOT NULL,
                weight_unit VARCHAR(3) NOT NULL,
                packages INT DEFAULT 1 NOT NULL,
                items JSON NOT NULL,
                sale_id INT DEFAULT NULL,
                observations TEXT DEFAULT NULL,
                status VARCHAR(10) DEFAULT 'PENDIENTE' NOT NULL,
                hash TEXT DEFAULT NULL,
                qr_data TEXT DEFAULT NULL,
                pdf_url VARCHAR(500) DEFAULT NULL,
                xml_url VARCHAR(500) DEFAULT NULL,
                error_message TEXT DEFAULT NULL,
                provider_response JSON DEFAULT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY(id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS uq_dispatch_number ON dispatch_guides (series, correlative)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_dispatch_status ON dispatch_guides (status)');
        $this->addSql('ALTER TABLE dispatch_guides ADD CONSTRAINT fk_dispatch_sale FOREIGN KEY (sale_id) REFERENCES sales (id) ON DELETE SET NULL');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS dispatch_guides');
    }
}
