<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Adición A5 — Promociones (§24.3), submódulo de Ventas.
 */
final class Version20260712180000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Crea la tabla promotions (Adición A5 · promociones)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE promotions (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(30) NOT NULL, name VARCHAR(120) NOT NULL, type VARCHAR(20) NOT NULL, discount_percent NUMERIC(5, 2) DEFAULT NULL, scope_type VARCHAR(20) NOT NULL, scope_ref_id INT DEFAULT NULL, bonus_subject_type VARCHAR(40) DEFAULT NULL, bonus_subject_id INT DEFAULT NULL, bonus_label VARCHAR(200) DEFAULT NULL, bonus_quantity INT DEFAULT NULL, start_date DATE NOT NULL, end_date DATE NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uq_promotion_code ON promotions (code) WHERE (deleted_at IS NULL)');
        $this->addSql('CREATE INDEX idx_promotion_dates ON promotions (start_date, end_date)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE promotions');
    }
}
