<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260711151641 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE service_order_items (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, item_type VARCHAR(10) NOT NULL, description VARCHAR(250) NOT NULL, quantity INT NOT NULL, unit_price NUMERIC(12, 2) NOT NULL, line_total NUMERIC(12, 2) NOT NULL, service_order_id INT NOT NULL, spare_part_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AE1ABB1C74E93605 ON service_order_items (service_order_id)');
        $this->addSql('CREATE INDEX IDX_AE1ABB1C49B7A72 ON service_order_items (spare_part_id)');
        $this->addSql('CREATE TABLE service_orders (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, order_number VARCHAR(20) NOT NULL, motorcycle_description VARCHAR(200) DEFAULT NULL, plate VARCHAR(10) DEFAULT NULL, mileage INT DEFAULT NULL, entry_date DATE NOT NULL, estimated_date DATE DEFAULT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, mechanic_name VARCHAR(100) DEFAULT NULL, diagnosis TEXT DEFAULT NULL, notes TEXT DEFAULT NULL, status VARCHAR(20) DEFAULT \'RECIBIDA\' NOT NULL, invoice_sale_id INT DEFAULT NULL, customer_id INT NOT NULL, motorcycle_unit_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_DBE8F8D89395C3F3 ON service_orders (customer_id)');
        $this->addSql('CREATE INDEX IDX_DBE8F8D827E831E5 ON service_orders (motorcycle_unit_id)');
        $this->addSql('CREATE INDEX idx_service_order_status ON service_orders (status)');
        $this->addSql('CREATE UNIQUE INDEX uq_service_order_number ON service_orders (order_number)');
        $this->addSql('ALTER TABLE service_order_items ADD CONSTRAINT FK_AE1ABB1C74E93605 FOREIGN KEY (service_order_id) REFERENCES service_orders (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE service_order_items ADD CONSTRAINT FK_AE1ABB1C49B7A72 FOREIGN KEY (spare_part_id) REFERENCES spare_parts (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE service_orders ADD CONSTRAINT FK_DBE8F8D89395C3F3 FOREIGN KEY (customer_id) REFERENCES customers (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE service_orders ADD CONSTRAINT FK_DBE8F8D827E831E5 FOREIGN KEY (motorcycle_unit_id) REFERENCES motorcycle_units (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE service_order_items DROP CONSTRAINT FK_AE1ABB1C74E93605');
        $this->addSql('ALTER TABLE service_order_items DROP CONSTRAINT FK_AE1ABB1C49B7A72');
        $this->addSql('ALTER TABLE service_orders DROP CONSTRAINT FK_DBE8F8D89395C3F3');
        $this->addSql('ALTER TABLE service_orders DROP CONSTRAINT FK_DBE8F8D827E831E5');
        $this->addSql('DROP TABLE service_order_items');
        $this->addSql('DROP TABLE service_orders');
    }
}
