<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260711142345 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE purchase_items (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, item_type VARCHAR(20) NOT NULL, description VARCHAR(250) NOT NULL, quantity INT NOT NULL, unit_price NUMERIC(12, 2) NOT NULL, discount NUMERIC(12, 2) NOT NULL, line_total NUMERIC(12, 2) NOT NULL, purchase_id INT NOT NULL, spare_part_id INT DEFAULT NULL, motorcycle_unit_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_35D56A67558FBEB9 ON purchase_items (purchase_id)');
        $this->addSql('CREATE INDEX IDX_35D56A6749B7A72 ON purchase_items (spare_part_id)');
        $this->addSql('CREATE INDEX IDX_35D56A6727E831E5 ON purchase_items (motorcycle_unit_id)');
        $this->addSql('CREATE TABLE purchases (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, purchase_number VARCHAR(20) NOT NULL, purchase_date DATE NOT NULL, document_type VARCHAR(15) NOT NULL, series VARCHAR(10) DEFAULT NULL, document_number VARCHAR(20) DEFAULT NULL, currency VARCHAR(3) DEFAULT \'PEN\' NOT NULL, subtotal NUMERIC(12, 2) NOT NULL, igv NUMERIC(12, 2) NOT NULL, total NUMERIC(12, 2) NOT NULL, status VARCHAR(15) DEFAULT \'REGISTRADA\' NOT NULL, notes TEXT DEFAULT NULL, supplier_id INT NOT NULL, payment_method_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AA6431FE2ADD6D8C ON purchases (supplier_id)');
        $this->addSql('CREATE INDEX IDX_AA6431FE5AA1164F ON purchases (payment_method_id)');
        $this->addSql('CREATE INDEX idx_purchase_date ON purchases (purchase_date)');
        $this->addSql('CREATE INDEX idx_purchase_status ON purchases (status)');
        $this->addSql('CREATE UNIQUE INDEX uq_purchase_number ON purchases (purchase_number)');
        $this->addSql('ALTER TABLE purchase_items ADD CONSTRAINT FK_35D56A67558FBEB9 FOREIGN KEY (purchase_id) REFERENCES purchases (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchase_items ADD CONSTRAINT FK_35D56A6749B7A72 FOREIGN KEY (spare_part_id) REFERENCES spare_parts (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchase_items ADD CONSTRAINT FK_35D56A6727E831E5 FOREIGN KEY (motorcycle_unit_id) REFERENCES motorcycle_units (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchases ADD CONSTRAINT FK_AA6431FE2ADD6D8C FOREIGN KEY (supplier_id) REFERENCES suppliers (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchases ADD CONSTRAINT FK_AA6431FE5AA1164F FOREIGN KEY (payment_method_id) REFERENCES catalog_items (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE purchase_items DROP CONSTRAINT FK_35D56A67558FBEB9');
        $this->addSql('ALTER TABLE purchase_items DROP CONSTRAINT FK_35D56A6749B7A72');
        $this->addSql('ALTER TABLE purchase_items DROP CONSTRAINT FK_35D56A6727E831E5');
        $this->addSql('ALTER TABLE purchases DROP CONSTRAINT FK_AA6431FE2ADD6D8C');
        $this->addSql('ALTER TABLE purchases DROP CONSTRAINT FK_AA6431FE5AA1164F');
        $this->addSql('DROP TABLE purchase_items');
        $this->addSql('DROP TABLE purchases');
    }
}
