<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260711004002 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE customers (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, document_type VARCHAR(15) NOT NULL, document_number VARCHAR(20) NOT NULL, name VARCHAR(200) NOT NULL, trade_name VARCHAR(150) DEFAULT NULL, address VARCHAR(200) DEFAULT NULL, district VARCHAR(100) DEFAULT NULL, province VARCHAR(100) DEFAULT NULL, department VARCHAR(100) DEFAULT NULL, phone VARCHAR(20) DEFAULT NULL, mobile VARCHAR(20) DEFAULT NULL, email VARCHAR(150) DEFAULT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_customer_name ON customers (name)');
        $this->addSql('CREATE UNIQUE INDEX uq_customer_document ON customers (document_type, document_number) WHERE (deleted_at IS NULL)');
        $this->addSql('CREATE TABLE suppliers (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ruc VARCHAR(11) NOT NULL, business_name VARCHAR(200) NOT NULL, trade_name VARCHAR(150) DEFAULT NULL, address VARCHAR(200) DEFAULT NULL, city VARCHAR(100) DEFAULT NULL, phone VARCHAR(20) DEFAULT NULL, email VARCHAR(150) DEFAULT NULL, contact_person VARCHAR(150) DEFAULT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_supplier_business_name ON suppliers (business_name)');
        $this->addSql('CREATE UNIQUE INDEX uq_supplier_ruc ON suppliers (ruc) WHERE (deleted_at IS NULL)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE customers');
        $this->addSql('DROP TABLE suppliers');
    }
}
