<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Clientes · Catálogo administrable de tipos de cliente con % de descuento.
 * Reemplaza la columna string customer_type por una FK a customer_types.
 */
final class Version20260807130000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Tipos de cliente administrables (customer_types) con descuento por defecto';
    }

    public function up(Schema $schema): void
    {
        // 1) Catálogo de tipos.
        $this->addSql('CREATE TABLE IF NOT EXISTS customer_types (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            name VARCHAR(60) NOT NULL,
            discount_percent NUMERIC(5, 2) DEFAULT \'0.00\' NOT NULL,
            is_active BOOLEAN DEFAULT true NOT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
            PRIMARY KEY (id)
        )');
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS uq_customer_type_name ON customer_types (name) WHERE (deleted_at IS NULL)');

        // 2) Siembra de tipos por defecto (editables luego).
        foreach ([
            ['Público General', '0.00'],
            ['Cliente Frecuente', '5.00'],
            ['Corporativo / Empresa', '8.00'],
            ['Mayorista', '10.00'],
            ['VIP', '15.00'],
        ] as [$name, $pct]) {
            $this->addSql(
                'INSERT INTO customer_types (name, discount_percent, is_active, created_at, updated_at)
                 SELECT :n, :p, true, NOW(), NOW()
                 WHERE NOT EXISTS (SELECT 1 FROM customer_types WHERE name = :n)',
                ['n' => $name, 'p' => $pct],
            );
        }

        // 3) FK en customers y limpieza de la columna string previa.
        $this->addSql('ALTER TABLE customers ADD COLUMN IF NOT EXISTS customer_type_id INT DEFAULT NULL');
        $this->addSql('CREATE INDEX IF NOT EXISTS IDX_customers_customer_type ON customers (customer_type_id)');
        $this->addSql('ALTER TABLE customers DROP CONSTRAINT IF EXISTS FK_customers_customer_type');
        $this->addSql('ALTER TABLE customers ADD CONSTRAINT FK_customers_customer_type
            FOREIGN KEY (customer_type_id) REFERENCES customer_types (id) ON DELETE SET NULL');

        // Los clientes existentes pasan a "Público General".
        $this->addSql("UPDATE customers
            SET customer_type_id = (SELECT id FROM customer_types WHERE name = 'Público General' LIMIT 1)
            WHERE customer_type_id IS NULL");

        // Elimina la columna string anterior (si existía).
        $this->addSql('ALTER TABLE customers DROP COLUMN IF EXISTS customer_type');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE customers DROP CONSTRAINT IF EXISTS FK_customers_customer_type');
        $this->addSql('ALTER TABLE customers DROP COLUMN IF EXISTS customer_type_id');
        $this->addSql('DROP TABLE IF EXISTS customer_types');
    }
}
