<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Adición A6 — Arquitectura de pasarelas de pago (§24.8).
 * Registro estructurado de transacciones (v1: pasarela manual).
 */
final class Version20260712210000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Crea la tabla payment_transactions (Adición A6 · pasarelas de pago)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE payment_transactions (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, sale_id INT DEFAULT NULL, sale_number VARCHAR(30) DEFAULT NULL, customer_label VARCHAR(200) DEFAULT NULL, method VARCHAR(20) NOT NULL, amount NUMERIC(12, 2) NOT NULL, currency VARCHAR(3) DEFAULT \'PEN\' NOT NULL, status VARCHAR(20) DEFAULT \'PENDING\' NOT NULL, gateway VARCHAR(40) NOT NULL, operation_number VARCHAR(60) DEFAULT NULL, response_payload JSON DEFAULT NULL, notes VARCHAR(255) DEFAULT NULL, created_by VARCHAR(100) DEFAULT NULL, validated_by VARCHAR(100) DEFAULT NULL, validated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_payment_tx_status ON payment_transactions (status)');
        $this->addSql('CREATE INDEX idx_payment_tx_sale ON payment_transactions (sale_id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE payment_transactions');
    }
}
