<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260711020655 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE motorcycle_models (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, model VARCHAR(100) NOT NULL, version VARCHAR(100) DEFAULT NULL, model_year INT NOT NULL, engine_capacity VARCHAR(30) DEFAULT NULL, engine_type VARCHAR(100) DEFAULT NULL, power VARCHAR(50) DEFAULT NULL, fuel_type VARCHAR(30) DEFAULT NULL, transmission VARCHAR(50) DEFAULT NULL, tank_capacity VARCHAR(30) DEFAULT NULL, weight VARCHAR(30) DEFAULT NULL, colors VARCHAR(200) DEFAULT NULL, warranty_months INT DEFAULT NULL, reference_price NUMERIC(12, 2) DEFAULT NULL, image_path VARCHAR(255) DEFAULT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, brand_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D1781BA544F5D008 ON motorcycle_models (brand_id)');
        $this->addSql('CREATE UNIQUE INDEX uq_moto_model ON motorcycle_models (brand_id, model, version, model_year) WHERE (deleted_at IS NULL)');
        $this->addSql('CREATE TABLE motorcycle_units (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, internal_code VARCHAR(20) NOT NULL, vin VARCHAR(17) NOT NULL, engine_number VARCHAR(30) DEFAULT NULL, chassis_number VARCHAR(30) DEFAULT NULL, series VARCHAR(30) DEFAULT NULL, manufacture_year INT DEFAULT NULL, color VARCHAR(50) NOT NULL, entry_date DATE NOT NULL, purchase_date DATE DEFAULT NULL, purchase_price NUMERIC(12, 2) DEFAULT NULL, sale_price NUMERIC(12, 2) DEFAULT NULL, status VARCHAR(20) NOT NULL, location VARCHAR(100) DEFAULT NULL, notes TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, model_id INT NOT NULL, supplier_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F23322617975B7E7 ON motorcycle_units (model_id)');
        $this->addSql('CREATE INDEX IDX_F23322612ADD6D8C ON motorcycle_units (supplier_id)');
        $this->addSql('CREATE INDEX idx_unit_status ON motorcycle_units (status)');
        $this->addSql('CREATE UNIQUE INDEX uq_unit_vin ON motorcycle_units (vin)');
        $this->addSql('CREATE UNIQUE INDEX uq_unit_engine_number ON motorcycle_units (engine_number)');
        $this->addSql('CREATE UNIQUE INDEX uq_unit_internal_code ON motorcycle_units (internal_code) WHERE (deleted_at IS NULL)');
        $this->addSql('ALTER TABLE motorcycle_models ADD CONSTRAINT FK_D1781BA544F5D008 FOREIGN KEY (brand_id) REFERENCES catalog_items (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE motorcycle_units ADD CONSTRAINT FK_F23322617975B7E7 FOREIGN KEY (model_id) REFERENCES motorcycle_models (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE motorcycle_units ADD CONSTRAINT FK_F23322612ADD6D8C FOREIGN KEY (supplier_id) REFERENCES suppliers (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE motorcycle_models DROP CONSTRAINT FK_D1781BA544F5D008');
        $this->addSql('ALTER TABLE motorcycle_units DROP CONSTRAINT FK_F23322617975B7E7');
        $this->addSql('ALTER TABLE motorcycle_units DROP CONSTRAINT FK_F23322612ADD6D8C');
        $this->addSql('DROP TABLE motorcycle_models');
        $this->addSql('DROP TABLE motorcycle_units');
    }
}
